name: Trigger Garden Astro Fetch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger garden-astro workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/narze/garden-astro/dispatches \
            -d '{"event_type": "fetch_second_brain"}'
