name: Trigger Second Brain Fetch
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger garden-astro workflow
        run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -w "%{http_code}" \
            -o /dev/null \
            -s \
            https://api.github.com/repos/narze/garden-astro/dispatches \
            -d '{"event_type": "fetch_second_brain"}')
          
          if [[ "$response" =~ ^2[0-9]{2}$ ]]; then
            echo "Successfully triggered workflow"
          else
            echo "Failed to trigger workflow. HTTP status code: $response"
            exit 1
          fi
